# Generated by Django 4.1 on 2022-09-09 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Punnam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=90)),
                ('Description', models.TextField()),
                ('Marrige_Status', models.BooleanField(default='False')),
                ('Qualification', models.CharField(max_length=20)),
                ('kids', models.IntegerField(default='False', max_length=4)),
            ],
        ),
    ]
